# =============================================================================
# Vivado Automation Script: Project-Based Synthesis & Implementation
# =============================================================================

# run with: vivado -mode batch -source run_synth.tcl

# Anchor paths to boards/test/ and repository root
set script_dir [file dirname [file normalize [info script]]]
set repo_root [file normalize "$script_dir/../../.."]

# Debug output to verify paths in Vivado output
puts "========================================================"
puts "DEBUG PATHS:"
puts "  Script Dir: $script_dir"
puts "  Repo Root:  $repo_root"
puts "========================================================"

# Load common utility scripts
source "$repo_root/fpga/common/utils.tcl"

# Project settings
set proj_name   "test_project"
set top_module  "soc"
#set target_part "xc7a35tcsg324-1"
set target_part "xczu9eg-ffvb1156-2-e"

# Output directories (grouped inside boards/test/build/)
set build_dir   "$script_dir/build"
set proj_dir    "$build_dir/project"
set output_dir  "$build_dir/output"

# Source locations
set rtl_dir     "$repo_root/rtl"
set common_dir  "$repo_root/common"
set xdc_file    "$script_dir/constraints/constraints.xdc"

# Create output folders
file mkdir $proj_dir
file mkdir $output_dir

# Close any accidentally open projects just in case
catch {close_project}

# Create the project (Fixes the "No open project" exception)
create_project -force $proj_name $proj_dir -part $target_part

# Import sources via common helper
import_filelist "$repo_root/sources.f"

# =============================================================================
# PRINT AND SAVE RESOLVED VIVADO FILELIST
# =============================================================================
set filelist_out "$output_dir/resolved_filelist.f"
set fp [open $filelist_out w]

puts "\n=================== VIVADO RESOLVED FILES ==================="

foreach file [get_files -of_objects [get_filesets sources_1]] {
    # 1. Print to console / terminal
    puts "  $file"
    
    # 2. Write to disk
    puts $fp $file
}

close $fp

puts "============================================================="
puts "Filelist saved to: $filelist_out\n"

# Import constraints
read_xdc "$script_dir/constraints/constraints.xdc"

# =============================================================================
# DONT_TOUCH FOR UNFINISHED RTL (DYNAMIC CONSTRAINTS METHOD)
# =============================================================================
# Dynamically generate an XDC constraint file into the build directory
set dynamic_xdc "$build_dir/dont_touch_all.xdc"
set fh [open $dynamic_xdc w]
puts $fh "# Automatically generated by run_synth.tcl to protect unfinished RTL"

# ONLY target hierarchical instances (the module wrappers). 
# This prevents flattening and boundary optimization without bloat.
puts $fh "set_property DONT_TOUCH TRUE \[get_cells -hierarchical -filter {IS_PRIMITIVE == 0}\]"

close $fh

# Read the generated XDC file into the constraints fileset
read_xdc $dynamic_xdc
# =============================================================================

# Set top module
set_property top $top_module [get_filesets sources_1]
update_compile_order -fileset sources_1

# Apply Out-of-Context mode and disable flattening globally
set_property -name {STEPS.SYNTH_DESIGN.ARGS.MORE OPTIONS} -value {-mode out_of_context -flatten_hierarchy none} -objects [get_runs synth_1]

# out-of-context mode
#set_property -name {STEPS.SYNTH_DESIGN.ARGS.MORE OPTIONS} -value {-mode out_of_context} -objects [get_runs synth_1]

# Run Synthesis
puts "--- STARTING SYNTHESIS ---"
launch_runs synth_1 -jobs 4
wait_on_run synth_1

# Check for synthesis errors
if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
    error "ERROR: Synthesis failed!"
}

# Open Synthesis to write reports
open_run synth_1
write_checkpoint -force $output_dir/post_synth.dcp
report_utilization -file $output_dir/post_synth_util.txt
show_schematic [get_cells]
#write_schematic -format pdf -force "$output_dir/synth_schematic.pdf"
report_utilization -hierarchical -file $output_dir/hierarchy_breakdown.txt

# Run Implementation (Optimize, Place, Route)
puts "--- STARTING IMPLEMENTATION ---"
launch_runs impl_1 -to_step route_design -jobs 4
wait_on_run impl_1

# Check for implementation errors
if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
    error "ERROR: Implementation failed!"
}

# Open Implementation to extract final reports
open_run impl_1
write_checkpoint -force $output_dir/post_route.dcp
report_timing_summary -file $output_dir/post_route_timing_summary.txt
report_utilization -file $output_dir/post_route_util.txt
report_power -file $output_dir/post_route_power.txt
show_schematic [get_cells]
#write_schematic -format pdf -force "$output_dir/impl_schematic.pdf"
report_utilization -hierarchical -file $output_dir/hierarchy_breakdown.txt

puts "--- VIVADO FLOW COMPLETED SUCCESSFULLY ---"
exit
